# Generated by Django 4.0.3 on 2023-10-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(blank=True, max_length=255)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('insight', models.TextField()),
                ('url', models.CharField(max_length=512)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('start_year', models.CharField(blank=True, max_length=255)),
                ('impact', models.CharField(blank=True, max_length=255)),
                ('added', models.CharField(blank=True, max_length=255)),
                ('published', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('relevance', models.IntegerField(blank=True, null=True)),
                ('pestle', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('title', models.TextField()),
                ('likelihood', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
